/*
 * Inference Service for Multi-Instance Image Segmentation
 * A functional service for multi-instance segmentation of consumer products and retail images.
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.instance_segmentor_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ImageResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-18T23:16:04.173Z")
public class ImageResult {
  @SerializedName("imageName")
  private String imageName = null;

  @SerializedName("imageString")
  private String imageString = null;

  public ImageResult imageName(String imageName) {
    this.imageName = imageName;
    return this;
  }

   /**
   * Filename of incoming request.
   * @return imageName
  **/
  @ApiModelProperty(value = "Filename of incoming request.")
  public String getImageName() {
    return imageName;
  }

  public void setImageName(String imageName) {
    this.imageName = imageName;
  }

  public ImageResult imageString(String imageString) {
    this.imageString = imageString;
    return this;
  }

   /**
   * Result image in form of base64 string.
   * @return imageString
  **/
  @ApiModelProperty(value = "Result image in form of base64 string.")
  public String getImageString() {
    return imageString;
  }

  public void setImageString(String imageString) {
    this.imageString = imageString;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageResult imageResult = (ImageResult) o;
    return Objects.equals(this.imageName, imageResult.imageName) &&
        Objects.equals(this.imageString, imageResult.imageString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imageName, imageString);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageResult {\n");
    
    sb.append("    imageName: ").append(toIndentedString(imageName)).append("\n");
    sb.append("    imageString: ").append(toIndentedString(imageString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

