/*
 * Inference Service for Multi-Instance Image Segmentation
 * A functional service for multi-instance segmentation of consumer products and retail images.
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.instance_segmentor_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * SegmentationDetailsBbox
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-18T23:16:04.173Z")
public class SegmentationDetailsBbox {
  @SerializedName("x1")
  private BigDecimal x1 = null;

  @SerializedName("x2")
  private BigDecimal x2 = null;

  @SerializedName("y1")
  private BigDecimal y1 = null;

  @SerializedName("y2")
  private BigDecimal y2 = null;

  public SegmentationDetailsBbox x1(BigDecimal x1) {
    this.x1 = x1;
    return this;
  }

   /**
   * The x-coordinate of the top left corner of the bounding box.
   * @return x1
  **/
  @ApiModelProperty(value = "The x-coordinate of the top left corner of the bounding box.")
  public BigDecimal getX1() {
    return x1;
  }

  public void setX1(BigDecimal x1) {
    this.x1 = x1;
  }

  public SegmentationDetailsBbox x2(BigDecimal x2) {
    this.x2 = x2;
    return this;
  }

   /**
   * The x-coordinate of the bottom right corner of the bounding box.
   * @return x2
  **/
  @ApiModelProperty(value = "The x-coordinate of the bottom right corner of the bounding box.")
  public BigDecimal getX2() {
    return x2;
  }

  public void setX2(BigDecimal x2) {
    this.x2 = x2;
  }

  public SegmentationDetailsBbox y1(BigDecimal y1) {
    this.y1 = y1;
    return this;
  }

   /**
   * The y-coordinate of the top left corner of the bounding box.
   * @return y1
  **/
  @ApiModelProperty(value = "The y-coordinate of the top left corner of the bounding box.")
  public BigDecimal getY1() {
    return y1;
  }

  public void setY1(BigDecimal y1) {
    this.y1 = y1;
  }

  public SegmentationDetailsBbox y2(BigDecimal y2) {
    this.y2 = y2;
    return this;
  }

   /**
   * The y-coordinate of the bottom right corner of the bounding box.
   * @return y2
  **/
  @ApiModelProperty(value = "The y-coordinate of the bottom right corner of the bounding box.")
  public BigDecimal getY2() {
    return y2;
  }

  public void setY2(BigDecimal y2) {
    this.y2 = y2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SegmentationDetailsBbox segmentationDetailsBbox = (SegmentationDetailsBbox) o;
    return Objects.equals(this.x1, segmentationDetailsBbox.x1) &&
        Objects.equals(this.x2, segmentationDetailsBbox.x2) &&
        Objects.equals(this.y1, segmentationDetailsBbox.y1) &&
        Objects.equals(this.y2, segmentationDetailsBbox.y2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(x1, x2, y1, y2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SegmentationDetailsBbox {\n");
    
    sb.append("    x1: ").append(toIndentedString(x1)).append("\n");
    sb.append("    x2: ").append(toIndentedString(x2)).append("\n");
    sb.append("    y1: ").append(toIndentedString(y1)).append("\n");
    sb.append("    y2: ").append(toIndentedString(y2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

