/*
 * Inference Service for Multi-Instance Image Segmentation
 * A functional service for multi-instance segmentation of consumer products and retail images.
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.instance_segmentor_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.instance_segmentor_api.model.SegmentationDetailsBbox;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * SegmentationDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-18T23:16:04.173Z")
public class SegmentationDetails {
  @SerializedName("bbox")
  private SegmentationDetailsBbox bbox = null;

  @SerializedName("classId")
  private BigDecimal classId = null;

  @SerializedName("className")
  private String className = null;

  @SerializedName("mask")
  private String mask = null;

  @SerializedName("score")
  private BigDecimal score = null;

  public SegmentationDetails bbox(SegmentationDetailsBbox bbox) {
    this.bbox = bbox;
    return this;
  }

   /**
   * Get bbox
   * @return bbox
  **/
  @ApiModelProperty(value = "")
  public SegmentationDetailsBbox getBbox() {
    return bbox;
  }

  public void setBbox(SegmentationDetailsBbox bbox) {
    this.bbox = bbox;
  }

  public SegmentationDetails classId(BigDecimal classId) {
    this.classId = classId;
    return this;
  }

   /**
   * Class ID of the detected object.
   * @return classId
  **/
  @ApiModelProperty(value = "Class ID of the detected object.")
  public BigDecimal getClassId() {
    return classId;
  }

  public void setClassId(BigDecimal classId) {
    this.classId = classId;
  }

  public SegmentationDetails className(String className) {
    this.className = className;
    return this;
  }

   /**
   * Name of the class of the detected object.
   * @return className
  **/
  @ApiModelProperty(value = "Name of the class of the detected object.")
  public String getClassName() {
    return className;
  }

  public void setClassName(String className) {
    this.className = className;
  }

  public SegmentationDetails mask(String mask) {
    this.mask = mask;
    return this;
  }

   /**
   * Segementation in form of base64 encoded string of the detected object.
   * @return mask
  **/
  @ApiModelProperty(value = "Segementation in form of base64 encoded string of the detected object.")
  public String getMask() {
    return mask;
  }

  public void setMask(String mask) {
    this.mask = mask;
  }

  public SegmentationDetails score(BigDecimal score) {
    this.score = score;
    return this;
  }

   /**
   * Probability of the object detected.
   * @return score
  **/
  @ApiModelProperty(value = "Probability of the object detected.")
  public BigDecimal getScore() {
    return score;
  }

  public void setScore(BigDecimal score) {
    this.score = score;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SegmentationDetails segmentationDetails = (SegmentationDetails) o;
    return Objects.equals(this.bbox, segmentationDetails.bbox) &&
        Objects.equals(this.classId, segmentationDetails.classId) &&
        Objects.equals(this.className, segmentationDetails.className) &&
        Objects.equals(this.mask, segmentationDetails.mask) &&
        Objects.equals(this.score, segmentationDetails.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bbox, classId, className, mask, score);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SegmentationDetails {\n");
    
    sb.append("    bbox: ").append(toIndentedString(bbox)).append("\n");
    sb.append("    classId: ").append(toIndentedString(classId)).append("\n");
    sb.append("    className: ").append(toIndentedString(className)).append("\n");
    sb.append("    mask: ").append(toIndentedString(mask)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

