/*
 * Inference Service for Multi-Instance Image Segmentation
 * A functional service for multi-instance segmentation of consumer products and retail images.
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.instance_segmentor_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.instance_segmentor_api.model.SegmentationDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SegmentationResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-18T23:16:04.173Z")
public class SegmentationResult {
  @SerializedName("imageName")
  private String imageName = null;

  @SerializedName("results")
  private List<SegmentationDetails> results = null;

  public SegmentationResult imageName(String imageName) {
    this.imageName = imageName;
    return this;
  }

   /**
   * Filename of incoming request.
   * @return imageName
  **/
  @ApiModelProperty(value = "Filename of incoming request.")
  public String getImageName() {
    return imageName;
  }

  public void setImageName(String imageName) {
    this.imageName = imageName;
  }

  public SegmentationResult results(List<SegmentationDetails> results) {
    this.results = results;
    return this;
  }

  public SegmentationResult addResultsItem(SegmentationDetails resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<SegmentationDetails>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * List of object detected with their bounding boxes and segmentation details
   * @return results
  **/
  @ApiModelProperty(value = "List of object detected with their bounding boxes and segmentation details")
  public List<SegmentationDetails> getResults() {
    return results;
  }

  public void setResults(List<SegmentationDetails> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SegmentationResult segmentationResult = (SegmentationResult) o;
    return Objects.equals(this.imageName, segmentationResult.imageName) &&
        Objects.equals(this.results, segmentationResult.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imageName, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SegmentationResult {\n");
    
    sb.append("    imageName: ").append(toIndentedString(imageName)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

