/*
 * Inference Service for Customizable Image Classification
 * Service for pre-trained and customized image classification models. The pre-trained model detects the dominant objects present in an image from a set of [1000](http://image-net.org/challenges/LSVRC/2014/browse-synsets) categories such as trees, animals, food, vehicles, people, and more.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.image_classification_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.image_classification_api.model.Classification;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ClassificationResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-11T20:04:29.401Z")
public class ClassificationResult {
  @SerializedName("name")
  private String name = null;

  @SerializedName("results")
  private List<Classification> results = null;

  public ClassificationResult name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Filename of incoming request.
   * @return name
  **/
  @ApiModelProperty(value = "Filename of incoming request.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ClassificationResult results(List<Classification> results) {
    this.results = results;
    return this;
  }

  public ClassificationResult addResultsItem(Classification resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<Classification>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * List of Classifications and their probabilities
   * @return results
  **/
  @ApiModelProperty(value = "List of Classifications and their probabilities")
  public List<Classification> getResults() {
    return results;
  }

  public void setResults(List<Classification> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationResult classificationResult = (ClassificationResult) o;
    return Objects.equals(this.name, classificationResult.name) &&
        Objects.equals(this.results, classificationResult.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationResult {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

