/*
 * Inference Service for Optical Character Recognition (OCR)
 * Optical Character Recognition service takes an uploaded file and returns the text characters detected in the input.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.ocr_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Response upon successful processing.
 */
@ApiModel(description = "Response upon successful processing.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-29T21:35:14.638Z")
public class ResponseJobSubmitted {
  @SerializedName("id")
  private String id = null;

  @SerializedName("processedTime")
  private String processedTime = null;

  /**
   * Status of processing job.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING("PENDING");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  public ResponseJobSubmitted id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Request identifier, used for downloading the corresponding processing result.
   * @return id
  **/
  @ApiModelProperty(value = "Request identifier, used for downloading the corresponding processing result.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResponseJobSubmitted processedTime(String processedTime) {
    this.processedTime = processedTime;
    return this;
  }

   /**
   * The point in time when the processing was completed.
   * @return processedTime
  **/
  @ApiModelProperty(value = "The point in time when the processing was completed.")
  public String getProcessedTime() {
    return processedTime;
  }

  public void setProcessedTime(String processedTime) {
    this.processedTime = processedTime;
  }

  public ResponseJobSubmitted status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status of processing job.
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Status of processing job.")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseJobSubmitted responseJobSubmitted = (ResponseJobSubmitted) o;
    return Objects.equals(this.id, responseJobSubmitted.id) &&
        Objects.equals(this.processedTime, responseJobSubmitted.processedTime) &&
        Objects.equals(this.status, responseJobSubmitted.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, processedTime, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseJobSubmitted {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    processedTime: ").append(toIndentedString(processedTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

