/*
 * Inference Service for Document Feature Extraction
 * Document Feature Extraction API is capable of extracting feature vectors for any given document which can be used for comparison, informational retrieval, clustering or further processing
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.document_feature_extraction_api.api;

import com.sap.apibhub.sdk.client.ApiCallback;
import com.sap.apibhub.sdk.client.ApiClient;
import com.sap.apibhub.sdk.client.ApiException;
import com.sap.apibhub.sdk.client.ApiResponse;
import com.sap.apibhub.sdk.client.Configuration;
import com.sap.apibhub.sdk.client.Pair;
import com.sap.apibhub.sdk.client.ProgressRequestBody;
import com.sap.apibhub.sdk.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.io.File;
import com.sap.apibhub.sdk.document_feature_extraction_api.model.Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DocumentFeatureExtractionApi {
    private ApiClient apiClient;

    public DocumentFeatureExtractionApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DocumentFeatureExtractionApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for inferenceSyncPost */
    private com.squareup.okhttp.Call inferenceSyncPostCall(File files, String texts, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/inference_sync".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        if (files != null)
        localVarFormParams.put("files", files);
        if (texts != null)
        localVarFormParams.put("texts", texts);

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY"  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call inferenceSyncPostValidateBeforeCall(File files, String texts, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = inferenceSyncPostCall(files, texts, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 
     * The Document Feature Extraction inference service (asynchronous) accepts multiple &lt;b&gt;text files&lt;/b&gt; or a single &lt;b&gt;zip&lt;/b&gt; of text files as input, and returns the name of the files with the corresponding feature vector.&lt;br&gt;&lt;br&gt;  
     * @param files This parameter is required. &lt;br&gt;The file or list of file(s) to be uploaded. &lt;br&gt;Either one Archive file, one text file, or multiple text files are supported: &lt;ul&gt; &lt;li&gt;Archive file - &lt;i&gt;one file with the format &#39;*_/zip&#39;&lt;/i&gt;&lt;/li&gt; &lt;li&gt;Text files - &lt;i&gt;files with .txt extension&lt;/i&gt;&lt;/li&gt; &lt;/ul&gt; &lt;ul&gt; &lt;/ul&gt; (optional)
     * @param texts This parameter is required only if the parameter &lt;i&gt;files&lt;/i&gt; is null or empty. &lt;br&gt;The parameter &lt;i&gt;texts&lt;/i&gt; is the text to be uploaded.             (optional)
     * @return Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Response inferenceSyncPost(File files, String texts) throws ApiException {
        ApiResponse<Response> resp = inferenceSyncPostWithHttpInfo(files, texts);
        return resp.getData();
    }

    /**
     * 
     * The Document Feature Extraction inference service (asynchronous) accepts multiple &lt;b&gt;text files&lt;/b&gt; or a single &lt;b&gt;zip&lt;/b&gt; of text files as input, and returns the name of the files with the corresponding feature vector.&lt;br&gt;&lt;br&gt;  
     * @param files This parameter is required. &lt;br&gt;The file or list of file(s) to be uploaded. &lt;br&gt;Either one Archive file, one text file, or multiple text files are supported: &lt;ul&gt; &lt;li&gt;Archive file - &lt;i&gt;one file with the format &#39;*_/zip&#39;&lt;/i&gt;&lt;/li&gt; &lt;li&gt;Text files - &lt;i&gt;files with .txt extension&lt;/i&gt;&lt;/li&gt; &lt;/ul&gt; &lt;ul&gt; &lt;/ul&gt; (optional)
     * @param texts This parameter is required only if the parameter &lt;i&gt;files&lt;/i&gt; is null or empty. &lt;br&gt;The parameter &lt;i&gt;texts&lt;/i&gt; is the text to be uploaded.             (optional)
     * @return ApiResponse&lt;Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Response> inferenceSyncPostWithHttpInfo(File files, String texts) throws ApiException {
        com.squareup.okhttp.Call call = inferenceSyncPostValidateBeforeCall(files, texts, null, null);
        Type localVarReturnType = new TypeToken<Response>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * The Document Feature Extraction inference service (asynchronous) accepts multiple &lt;b&gt;text files&lt;/b&gt; or a single &lt;b&gt;zip&lt;/b&gt; of text files as input, and returns the name of the files with the corresponding feature vector.&lt;br&gt;&lt;br&gt;  
     * @param files This parameter is required. &lt;br&gt;The file or list of file(s) to be uploaded. &lt;br&gt;Either one Archive file, one text file, or multiple text files are supported: &lt;ul&gt; &lt;li&gt;Archive file - &lt;i&gt;one file with the format &#39;*_/zip&#39;&lt;/i&gt;&lt;/li&gt; &lt;li&gt;Text files - &lt;i&gt;files with .txt extension&lt;/i&gt;&lt;/li&gt; &lt;/ul&gt; &lt;ul&gt; &lt;/ul&gt; (optional)
     * @param texts This parameter is required only if the parameter &lt;i&gt;files&lt;/i&gt; is null or empty. &lt;br&gt;The parameter &lt;i&gt;texts&lt;/i&gt; is the text to be uploaded.             (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call inferenceSyncPostAsync(File files, String texts, final ApiCallback<Response> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = inferenceSyncPostValidateBeforeCall(files, texts, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Response>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
