/*
 * Inference Service for Face Detection
 * A functional service for detecting faces in an image / images
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.face_detection_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Declaration of a boundary box, with pixel numbers
 */
@ApiModel(description = "Declaration of a boundary box, with pixel numbers")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-28T20:17:18.267Z")
public class BoundaryBox {
  @SerializedName("top")
  private BigDecimal top = null;

  @SerializedName("bottom")
  private BigDecimal bottom = null;

  @SerializedName("left")
  private BigDecimal left = null;

  @SerializedName("right")
  private BigDecimal right = null;

  public BoundaryBox top(BigDecimal top) {
    this.top = top;
    return this;
  }

   /**
   * topmost pixel y-coordinate
   * @return top
  **/
  @ApiModelProperty(value = "topmost pixel y-coordinate")
  public BigDecimal getTop() {
    return top;
  }

  public void setTop(BigDecimal top) {
    this.top = top;
  }

  public BoundaryBox bottom(BigDecimal bottom) {
    this.bottom = bottom;
    return this;
  }

   /**
   * bottommost pixel y-coordinate
   * @return bottom
  **/
  @ApiModelProperty(value = "bottommost pixel y-coordinate")
  public BigDecimal getBottom() {
    return bottom;
  }

  public void setBottom(BigDecimal bottom) {
    this.bottom = bottom;
  }

  public BoundaryBox left(BigDecimal left) {
    this.left = left;
    return this;
  }

   /**
   * leftmost pixel x-coordinate
   * @return left
  **/
  @ApiModelProperty(value = "leftmost pixel x-coordinate")
  public BigDecimal getLeft() {
    return left;
  }

  public void setLeft(BigDecimal left) {
    this.left = left;
  }

  public BoundaryBox right(BigDecimal right) {
    this.right = right;
    return this;
  }

   /**
   * rightmost pixed x-coordinate
   * @return right
  **/
  @ApiModelProperty(value = "rightmost pixed x-coordinate")
  public BigDecimal getRight() {
    return right;
  }

  public void setRight(BigDecimal right) {
    this.right = right;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoundaryBox boundaryBox = (BoundaryBox) o;
    return Objects.equals(this.top, boundaryBox.top) &&
        Objects.equals(this.bottom, boundaryBox.bottom) &&
        Objects.equals(this.left, boundaryBox.left) &&
        Objects.equals(this.right, boundaryBox.right);
  }

  @Override
  public int hashCode() {
    return Objects.hash(top, bottom, left, right);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoundaryBox {\n");
    
    sb.append("    top: ").append(toIndentedString(top)).append("\n");
    sb.append("    bottom: ").append(toIndentedString(bottom)).append("\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    right: ").append(toIndentedString(right)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

