/*
 * Inference Service for Scene Text Recognition
 * A functional service for extracting texts from images.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.scene_text_recognition_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * ExtractedBoxesDetailsBoundingBox
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-29T16:35:00.011Z")
public class ExtractedBoxesDetailsBoundingBox {
  @SerializedName("x1")
  private BigDecimal x1 = null;

  @SerializedName("x2")
  private BigDecimal x2 = null;

  @SerializedName("x3")
  private BigDecimal x3 = null;

  @SerializedName("x4")
  private BigDecimal x4 = null;

  @SerializedName("y1")
  private BigDecimal y1 = null;

  @SerializedName("y2")
  private BigDecimal y2 = null;

  @SerializedName("y3")
  private BigDecimal y3 = null;

  @SerializedName("y4")
  private BigDecimal y4 = null;

  public ExtractedBoxesDetailsBoundingBox x1(BigDecimal x1) {
    this.x1 = x1;
    return this;
  }

   /**
   * Top-left x-coordinate of Bounding Box.
   * @return x1
  **/
  @ApiModelProperty(value = "Top-left x-coordinate of Bounding Box.")
  public BigDecimal getX1() {
    return x1;
  }

  public void setX1(BigDecimal x1) {
    this.x1 = x1;
  }

  public ExtractedBoxesDetailsBoundingBox x2(BigDecimal x2) {
    this.x2 = x2;
    return this;
  }

   /**
   * Top-right x-coordinate of Bounding Box.
   * @return x2
  **/
  @ApiModelProperty(value = "Top-right x-coordinate of Bounding Box.")
  public BigDecimal getX2() {
    return x2;
  }

  public void setX2(BigDecimal x2) {
    this.x2 = x2;
  }

  public ExtractedBoxesDetailsBoundingBox x3(BigDecimal x3) {
    this.x3 = x3;
    return this;
  }

   /**
   * Bottom-right x-coordinate of Bounding Box.
   * @return x3
  **/
  @ApiModelProperty(value = "Bottom-right x-coordinate of Bounding Box.")
  public BigDecimal getX3() {
    return x3;
  }

  public void setX3(BigDecimal x3) {
    this.x3 = x3;
  }

  public ExtractedBoxesDetailsBoundingBox x4(BigDecimal x4) {
    this.x4 = x4;
    return this;
  }

   /**
   * Bottom-left x-coordinate of Bounding Box.
   * @return x4
  **/
  @ApiModelProperty(value = "Bottom-left x-coordinate of Bounding Box.")
  public BigDecimal getX4() {
    return x4;
  }

  public void setX4(BigDecimal x4) {
    this.x4 = x4;
  }

  public ExtractedBoxesDetailsBoundingBox y1(BigDecimal y1) {
    this.y1 = y1;
    return this;
  }

   /**
   * Top-left y-coordinate of Bounding Box.
   * @return y1
  **/
  @ApiModelProperty(value = "Top-left y-coordinate of Bounding Box.")
  public BigDecimal getY1() {
    return y1;
  }

  public void setY1(BigDecimal y1) {
    this.y1 = y1;
  }

  public ExtractedBoxesDetailsBoundingBox y2(BigDecimal y2) {
    this.y2 = y2;
    return this;
  }

   /**
   * Top-right y-coordinate of Bounding Box.
   * @return y2
  **/
  @ApiModelProperty(value = "Top-right y-coordinate of Bounding Box.")
  public BigDecimal getY2() {
    return y2;
  }

  public void setY2(BigDecimal y2) {
    this.y2 = y2;
  }

  public ExtractedBoxesDetailsBoundingBox y3(BigDecimal y3) {
    this.y3 = y3;
    return this;
  }

   /**
   * Bottom-right y-coordinate of Bounding Box.
   * @return y3
  **/
  @ApiModelProperty(value = "Bottom-right y-coordinate of Bounding Box.")
  public BigDecimal getY3() {
    return y3;
  }

  public void setY3(BigDecimal y3) {
    this.y3 = y3;
  }

  public ExtractedBoxesDetailsBoundingBox y4(BigDecimal y4) {
    this.y4 = y4;
    return this;
  }

   /**
   * Bottom-left y-coordinate of Bounding Box.
   * @return y4
  **/
  @ApiModelProperty(value = "Bottom-left y-coordinate of Bounding Box.")
  public BigDecimal getY4() {
    return y4;
  }

  public void setY4(BigDecimal y4) {
    this.y4 = y4;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtractedBoxesDetailsBoundingBox extractedBoxesDetailsBoundingBox = (ExtractedBoxesDetailsBoundingBox) o;
    return Objects.equals(this.x1, extractedBoxesDetailsBoundingBox.x1) &&
        Objects.equals(this.x2, extractedBoxesDetailsBoundingBox.x2) &&
        Objects.equals(this.x3, extractedBoxesDetailsBoundingBox.x3) &&
        Objects.equals(this.x4, extractedBoxesDetailsBoundingBox.x4) &&
        Objects.equals(this.y1, extractedBoxesDetailsBoundingBox.y1) &&
        Objects.equals(this.y2, extractedBoxesDetailsBoundingBox.y2) &&
        Objects.equals(this.y3, extractedBoxesDetailsBoundingBox.y3) &&
        Objects.equals(this.y4, extractedBoxesDetailsBoundingBox.y4);
  }

  @Override
  public int hashCode() {
    return Objects.hash(x1, x2, x3, x4, y1, y2, y3, y4);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtractedBoxesDetailsBoundingBox {\n");
    
    sb.append("    x1: ").append(toIndentedString(x1)).append("\n");
    sb.append("    x2: ").append(toIndentedString(x2)).append("\n");
    sb.append("    x3: ").append(toIndentedString(x3)).append("\n");
    sb.append("    x4: ").append(toIndentedString(x4)).append("\n");
    sb.append("    y1: ").append(toIndentedString(y1)).append("\n");
    sb.append("    y2: ").append(toIndentedString(y2)).append("\n");
    sb.append("    y3: ").append(toIndentedString(y3)).append("\n");
    sb.append("    y4: ").append(toIndentedString(y4)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

