/*
 * Inference Service for Scene Text Recognition
 * A functional service for extracting texts from images.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.scene_text_recognition_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.scene_text_recognition_api.model.ExtractedBoxesDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ExtractedBoxesResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-29T16:35:00.011Z")
public class ExtractedBoxesResult {
  @SerializedName("imageName")
  private String imageName = null;

  @SerializedName("results")
  private List<ExtractedBoxesDetails> results = null;

  public ExtractedBoxesResult imageName(String imageName) {
    this.imageName = imageName;
    return this;
  }

   /**
   * Filename of incoming request.
   * @return imageName
  **/
  @ApiModelProperty(value = "Filename of incoming request.")
  public String getImageName() {
    return imageName;
  }

  public void setImageName(String imageName) {
    this.imageName = imageName;
  }

  public ExtractedBoxesResult results(List<ExtractedBoxesDetails> results) {
    this.results = results;
    return this;
  }

  public ExtractedBoxesResult addResultsItem(ExtractedBoxesDetails resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<ExtractedBoxesDetails>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * List of text objects detected with respective bounding boxes and text information.
   * @return results
  **/
  @ApiModelProperty(value = "List of text objects detected with respective bounding boxes and text information.")
  public List<ExtractedBoxesDetails> getResults() {
    return results;
  }

  public void setResults(List<ExtractedBoxesDetails> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtractedBoxesResult extractedBoxesResult = (ExtractedBoxesResult) o;
    return Objects.equals(this.imageName, extractedBoxesResult.imageName) &&
        Objects.equals(this.results, extractedBoxesResult.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imageName, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtractedBoxesResult {\n");
    
    sb.append("    imageName: ").append(toIndentedString(imageName)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

