/*
 * Inference Service for Scene Text Recognition
 * A functional service for extracting texts from images.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.scene_text_recognition_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.scene_text_recognition_api.model.ExtractedBoxesDetailsBoundingBox;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * ExtractedBoxesDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-29T16:35:00.011Z")
public class ExtractedBoxesDetails {
  @SerializedName("boundingBox")
  private ExtractedBoxesDetailsBoundingBox boundingBox = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("bboxAccuracy")
  private BigDecimal bboxAccuracy = null;

  public ExtractedBoxesDetails boundingBox(ExtractedBoxesDetailsBoundingBox boundingBox) {
    this.boundingBox = boundingBox;
    return this;
  }

   /**
   * Get boundingBox
   * @return boundingBox
  **/
  @ApiModelProperty(value = "")
  public ExtractedBoxesDetailsBoundingBox getBoundingBox() {
    return boundingBox;
  }

  public void setBoundingBox(ExtractedBoxesDetailsBoundingBox boundingBox) {
    this.boundingBox = boundingBox;
  }

  public ExtractedBoxesDetails text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Text present in the detected Bounding Box.
   * @return text
  **/
  @ApiModelProperty(value = "Text present in the detected Bounding Box.")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public ExtractedBoxesDetails bboxAccuracy(BigDecimal bboxAccuracy) {
    this.bboxAccuracy = bboxAccuracy;
    return this;
  }

   /**
   * Confidence in the text box detected.
   * @return bboxAccuracy
  **/
  @ApiModelProperty(value = "Confidence in the text box detected.")
  public BigDecimal getBboxAccuracy() {
    return bboxAccuracy;
  }

  public void setBboxAccuracy(BigDecimal bboxAccuracy) {
    this.bboxAccuracy = bboxAccuracy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtractedBoxesDetails extractedBoxesDetails = (ExtractedBoxesDetails) o;
    return Objects.equals(this.boundingBox, extractedBoxesDetails.boundingBox) &&
        Objects.equals(this.text, extractedBoxesDetails.text) &&
        Objects.equals(this.bboxAccuracy, extractedBoxesDetails.bboxAccuracy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boundingBox, text, bboxAccuracy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtractedBoxesDetails {\n");
    
    sb.append("    boundingBox: ").append(toIndentedString(boundingBox)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    bboxAccuracy: ").append(toIndentedString(bboxAccuracy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

