/*
 * Inference Service for Document Feature Extraction
 * Document Feature Extraction API is capable of extracting feature vectors for any given document which can be used for comparison, informational retrieval, clustering or further processing
 *
 * OpenAPI spec version: Alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
